use gtk::glib;
use sourceview5 as sourceview;
use std::{cell::Cell, cell::RefCell, rc::Rc};

use crate::state::DocState;
use crate::crypto;

#[derive(Clone)]
pub struct EditorCtx {
    pub window: adw::ApplicationWindow,
    pub notes_list: gtk::ListBox,
    pub search_entry: gtk::SearchEntry,
    pub rich_buffer: gtk::TextBuffer,
    pub rich_panel: gtk::ScrolledWindow,
    pub markdown_buffer: sourceview::Buffer,
    pub markdown_view: sourceview::View,
    pub markdown_panel: gtk::ScrolledWindow,
    pub split: gtk::Paned,
    pub status: gtk::Label,
    pub doc_label: gtk::Label,
    pub dirty_label: gtk::Label,
    pub tags_box: gtk::FlowBox,
    pub tag_entry: gtk::Entry,
    pub state: Rc<RefCell<DocState>>,
    pub vault_folder: Rc<RefCell<String>>,
    pub cached_key: Rc<RefCell<Option<crypto::CachedKey>>>,
    pub save_timeout_id: Rc<Cell<Option<glib::SourceId>>>,
    pub save_generation: Rc<Cell<u64>>,
    pub saving: Rc<Cell<bool>>,
    pub close_requested: Rc<Cell<bool>>,
    // HIG layout widgets
    pub split_view: adw::OverlaySplitView,
    pub toast_overlay: adw::ToastOverlay,
    pub toolbar: gtk::ScrolledWindow,
    pub tab_view: adw::TabView,
    pub tab_bar: adw::TabBar,
    pub tags_row: gtk::Box,
    pub breadcrumbs: gtk::Label,
    pub tag_filter_box: gtk::Box,
    pub meta_label: gtk::Label,
    pub search_bar: gtk::SearchBar,
    pub content_stack: gtk::Stack,
    pub source_toggle: gtk::Button,
    pub sync_timeout_id: Rc<Cell<Option<glib::SourceId>>>,
    pub search_timeout_id: Rc<Cell<Option<glib::SourceId>>>,
}

pub struct ContentPaneWidgets {
    pub toast_overlay: adw::ToastOverlay,
    pub content_toolbar_view: adw::ToolbarView,
    pub content_header: adw::HeaderBar,
    pub doc_label: gtk::Label,
    pub dirty_label: gtk::Label,
    pub toolbar_scroll: gtk::ScrolledWindow,
    pub tab_view: adw::TabView,
    pub tab_bar: adw::TabBar,
    pub breadcrumbs: gtk::Label,
    pub status_label: gtk::Label,
    pub meta_label: gtk::Label,
    pub status_bar: gtk::ActionBar,
    pub rich_buffer: gtk::TextBuffer,
    pub rich_view: gtk::TextView,
    pub rich_scroll: gtk::ScrolledWindow,
    pub md_buffer: sourceview::Buffer,
    pub md_view: sourceview::View,
    pub md_scroll: gtk::ScrolledWindow,
    pub split: gtk::Paned,
    pub tags_row: gtk::Box,
    pub tags_box: gtk::FlowBox,
    pub tag_entry: gtk::Entry,
    pub toolbar_widgets: ToolbarWidgets,
    pub source_toggle: gtk::Button,
    pub content_stack: gtk::Stack,
}

pub struct ToolbarWidgets {
    pub undo: gtk::Button,
    pub redo: gtk::Button,
    pub bold: gtk::Button,
    pub italic: gtk::Button,
    pub underline: gtk::Button,
    pub strike: gtk::Button,
    pub code: gtk::Button,
    pub block_popover: gtk::Popover,
    pub block_paragraph: gtk::Button,
    pub block_h1: gtk::Button,
    pub block_h2: gtk::Button,
    pub block_h3: gtk::Button,
    pub block_h4: gtk::Button,
    pub block_h5: gtk::Button,
    pub block_h6: gtk::Button,
    pub block_quote: gtk::Button,
    pub bullet: gtk::Button,
    pub ordered: gtk::Button,
    pub task: gtk::Button,
    pub link: gtk::Button,
    pub table: gtk::Button,
    pub rule: gtk::Button,
    pub fullscreen: gtk::Button,
    pub image: gtk::Button,
    pub code_block_popover: gtk::Popover,
    pub code_languages: Vec<(String, gtk::Button)>,
    pub mode: gtk::Button,
}
